name: Release

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install dependencies
        run: npm install -g vsce

      - name: Run package 
        run: vsce package

      - name: Publish build
        run: vsce publish patch --pat=$PAT
        env:
          PAT: ${{ secrets.PAT }}
